In [28]:
import sys
import math
import cv2 as cv
import numpy as np
def main(argv):
    
    default_file = 'try.png'
    src= cv.imread(default_file)
       
    img_hsv = cv.cvtColor(src, cv.COLOR_BGR2HSV)
    ## Gen lower mask (0-5) and upper mask (175-180) of RED
    mask1 = cv.inRange(img_hsv, (0,50,20), (5,255,255))
    mask2 = cv.inRange(img_hsv, (175,50,20), (180,255,255))


    ## Merge the mask and crop the red regions
    mask = cv.bitwise_or(mask1, mask2 )
    croped = cv.bitwise_and(src, src, mask=mask)
    
    ## Display
    cv.imshow("mask", mask)
    cv.imshow("croped", croped)
    
    dst = cv.Canny(src, 50, 200, None, 3)   
    
    # Copy edges to the images that will display the results in BGR
    cdst = cv.cvtColor(dst, cv.COLOR_GRAY2BGR)
    cdstP = np.copy(cdst)
    
    lines = cv.HoughLines(dst, 1, np.pi / 180, 150, None, 0, 0)
    
    if lines is not None:
        for i in range(0, len(lines)):
            rho = lines[i][0][0]
            theta = lines[i][0][1]
            a = math.cos(theta)
            b = math.sin(theta)
            x0 = a * rho
            y0 = b * rho
            pt1 = (int(x0 + 1000*(-b)), int(y0 + 1000*(a)))
            pt2 = (int(x0 - 1000*(-b)), int(y0 - 1000*(a)))
            cv.line(cdst, pt1, pt2, (0,0,255), 3, cv.LINE_AA)
    
    
    linesP = cv.HoughLinesP(dst, 1, np.pi / 180, 50, None, 50, 10)
    print(linesP)
    
    if linesP is not None:
        for i in range(0, len(linesP)):
            l = linesP[i][0]
            cv.line(cdstP, (l[0], l[1]), (l[2], l[3]), (0,0,255), 3, cv.LINE_AA)
            
    
    cv.imshow("Source", src)
    cv.imshow("Detected Lines (in red) - Standard Hough Line Transform", cdst)
    cv.imshow("Detected Lines (in red) - Probabilistic Line Transform", cdstP)
    
  
    
    cv.waitKey()
    return 0
    
if __name__ == "__main__":
    main(sys.argv[1:])

[[[1095  584 1095  116]]

 [[ 333  584  674  584]]

 [[ 466  564  827  539]]

 [[  35  284  199  453]]

 [[  68  365  203  505]]

 [[  17  311  119  417]]

 [[  29  124   58    0]]

 [[   1  256   32  119]]

 [[ 621   31  709   28]]

 [[ 615   17  728   12]]

 [[  49  272  137  206]]

 [[ 712  584  803  585]]

 [[1015  584 1067  585]]

 [[ 872  584  872  475]]

 [[ 675  583  830  572]]

 [[  16  260   89  214]]

 [[ 221  142  291   89]]

 [[ 224  138  284   93]]

 [[1095   19 1096  123]]

 [[ 421   40  497   34]]

 [[ 215  118  276   74]]

 [[ 962  120 1003  172]]

 [[1012  146 1047  204]]

 [[  15  262   73  225]]

 [[ 621  109  623    0]]

 [[1069   24 1095  100]]

 [[  37  287  113  365]]

 [[ 812  584  868  584]]

 [[ 383   32  441   24]]

 [[ 551  109  622  109]]

 [[1000  169 1026  220]]

 [[1072   52 1094  108]]

 [[ 807   34  871   56]]]
